### ISSUE TITLE
Add IConsulAclProvider support in ConsulRegistry

### ISSUE THREAD

**Issue by jdeneux** [Drawaes/CondenserDotNet#111]
Hi

I need to build a Configuration object from Consul with a specific token. But looks like  IConsulAclProvider is only available for the ServiceRegistry, not for the ConfigurationRegistry.
Can we update it ?

Thks
Julien

**Comment by Drawaes** [comment]
This should now be done. Please confirm it works for you and I can close the item.

Thanks

Tim

**Comment by jdeneux** [comment]
It’s working now thks !

**Comment by Drawaes** [comment]
Cool.
