### ISSUE TITLE
Add Method to deregister Service from Consul

### ISSUE THREAD

**Issue by Hunter21007** [Drawaes/CondenserDotNet#22]
Hello,

First: this is a Great work! Thanks for this.

I am actually playing around with consul and this library. And I often start the app in a container.
And also shutdown it. And start it again, multiple times with multiple instances.
This leaves stale service registrations on consul. And I have to deregister them manually.

It would be nice to have a method to deregister the service via code.
After ServiceManager.RegisteredService exist.

Thanks.

**Comment by Drawaes** [comment]
Good thinking. There are two approaches here that I can look into. 

1. An explicit deregister/finalize/dispose
2. Consul allows for deregistering a service after a health check has gone critical after x amount of time.

I think both would be useful, but I will do one first. Which is of most use to you?

Good to hear it's useful, I have an use for this and writing the same logic for every service was painful, so I am glad to hear it is also useful for other people!

**Comment by Hunter21007** [comment]
Found it: deregister_critical_service_after :)
This should be OK for docker, because there is no guarantee that the app was shut down correctly.

So registering service with this Param, would help to get rid of stale registrations.

**Comment by Drawaes** [comment]
.DeregisterIfCriticalAfterMinutes(10)
.DeregisterIfCriticalAfterTimeSpan(.....

That seem okay?

**Comment by Hunter21007** [comment]
Yes, sure!

**Comment by Drawaes** [comment]
#23

**Comment by Hunter21007** [comment]
Wow, really fast! Will check it...

**Comment by Hunter21007** [comment]
Hi, i am actually on:

```
git log -1
commit 354e9f300f0d1b042be93ab71ac784dddd4c2e9a
Author: Drawaes <seawardtim@gmail.com>
Date:   Sun Dec 11 01:36:44 2016 +0000

    Merged
```

Everything works

**Comment by Drawaes** [comment]
Cool I will add some integration tests tonight and merge the branch in. Please feel free to dump a list of anything else you might find helpful/useful.

Do you use your services behind IIS by any chance? I am interested in use cases other then my own.

**Comment by Hunter21007** [comment]
Sorry, but not.
I am targeting .netcore and nodejs/typescript.

Jurij Zahn
Sent from mobile device

Am 12.12.2016 12:13 nachm. schrieb "Tim Seaward" <notifications@github.com>:

**Comment by Hunter21007** [comment]
There is a chance to use it in our prototype webapp, which is actually ASP.NET5 on IIS,
But this app is already considered dead :)

**Comment by Drawaes** [comment]
No that's fine. The auto address discovery is a pain in IIS which I didn't
want to work on next! Ours are self hosted services as well.

**Comment by Hunter21007** [comment]
Works as expected with 0.6.1-199
Thanks!
