### ISSUE TITLE
Abstract behind some interfaces potentially allowing other providers

### ISSUE THREAD

**Issue by Drawaes** [Drawaes/CondenserDotNet#5]
Such as Redis for global locks, etc

**Comment by Hunter21007** [comment]
Today I have faced an Issue during writing tests as I have tried to mock servicemanager and config registry.
It is not possible. So abstracting them with interfaces would provide me better coverage of my code too :)

**Comment by Drawaes** [comment]
Agreed. This is something we have thought about. When I am back from
holidays I will have a crack at it.

**Comment by Drawaes** [comment]
So, I am keen to get this out of the way so I can move onto the router. Where would you like the main abstraction points/ how the composing would work?

**Comment by Drawaes** [comment]
@Hunter21007 This has now been done, is it okay for you?

**Comment by Hunter21007** [comment]
Hi, sorry I am out of Dev for last 3 weeks. (I help ops to maintain our oVirt systems) I will take a look once I am back :)

**Comment by Drawaes** [comment]
Sure no problem. I am going to close this issue for now. If you are unhappy with the level of abstraction feel free to open an issue for it :)
