### ISSUE TITLE
GetServiceInstanceAsync hangs if there is no consul instance

### ISSUE THREAD

**Issue by Drawaes** [Drawaes/CondenserDotNet#56]
When there is no consul service available the call hangs forever

**Comment by Drawaes** [comment]
Fixed by adding a timeout when waiting for the initial service list. Also made the fast path "we have a list of services" faster by not doing the await. Added a common exception for not being able to get the list

#57

**Comment by deanshackley** [comment]
Fixed with release 2.0.3
