### ISSUE TITLE
Support any tags without prefix

### ISSUE THREAD

**Issue by AlexeyUsachev** [Drawaes/CondenserDotNet#97]
now I can only use properties
            serviceManager.ProtocolSchemeTag = " protocolScheme-tag";
            serviceManager.SupportedUrls.Add("urlprefix-tag");
and I want to use
            serviceManager.Tags.Add("myTag");

**Comment by Drawaes** [comment]
Hi,

I have added a new property

```
serviceManager.CustomTags.Add("YourTag");
```

This is merged with a test and the packages built, nuget should index them shortly, version will be 3.0.7

https://github.com/Drawaes/CondenserDotNet/blob/master/test/Condenser.Tests.Integration/ServiceRegistrationFacts.cs#L33

**Comment by Drawaes** [comment]
If this satisfies your requirement please close :)

**Comment by Drawaes** [comment]
https://github.com/Drawaes/CondenserDotNet/pull/98

**Comment by Drawaes** [comment]
As this is done and released I am going to go ahead and close this now. Please reopen an issue if it doesn't meet your requirements

Thanks
